# This is a basic workflow to help you get started with Actions

name: woshipfull-check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

        # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install
      - run: make lint
      - run: make test

       - name: Test & publish code coverage
      #   # Publish code coverage on Code Climate
      #   # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.0.0
      #   # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ COVERAGE.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true